name: tasbeeh_app
description: A modern Tasbeeh app with multiple phrases, vibration, and saved counts.

# Flutter SDK
environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.4
  vibration: ^1.9.0

dev_dependencies:
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
