name: Flutter APK Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Get version from pubspec.yaml
        id: get_version
        run: |
          version=$(grep "version:" pubspec.yaml | awk '{print $2}')
          echo "APP_VERSION=$version" >> $GITHUB_ENV

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: tasbeeh_app-${{ env.APP_VERSION }}-release
          path: build/app/outputs/flutter-apk/app-release.apk